config/routes.rb
Rails.application.routes.draw do
  get 'search' , to: 'search#index'
  get 'shops/index'
  get 'shops/show'
  # resources :carts
  get 'carts', to: 'carts#index'
  resources :comments
  resources :products
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :line_items
  # resource :carts, only:[:show]
  resources :orders, only: [:index, :create, :show]
  resources :shops, only:[:index]
  root 'products#index'
  resources :orders, only: [:index, :show, :create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :content, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    # @comment = current_user.comments.new(comment_params)
  end

  # GET /comments/1/edit
  def edit

  end

  # POST /comments or /comments.json
  def create
    # @comment = Comment.new(comment_params_p)
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:error] = @comment.errors.full_messages
    end
    if @comment.save
      redirect_to product_path(params[:product_id])
    end


  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def comment_params_p
    #   params.require(:comment).permit(:content).merge(product_id: params[:product_id])
    # end

    def comment_params

      params.permit(:content, :product_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="py-3 border-bottom comment comment-<%= comment.id%>">
    <small class="d-inline-block mb-3 text-secondary border-bottom">Posted <%= time_ago_in_words(comment.created_at) %> ago.</small>
    <p><%= comment.content %></p>
    <div class="btn-group">
     <!--   <%# <%= link_to "Edit Comment", edit_post_comment_path(comment.post, comment), class: "btn btn-sm btn-outline-primary" %> %>
        <%= link_to "Delete Comment", comment_path(comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
        -->
    </div>
</div>

app/views/comments/_form.html.erb
<!--
<div class="form-group green-border-focus">
<form action="<%= product_comments_path(product)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%# <input type="text" name="comment[content]" id="content"> %>
  <textarea id="form7" class="md-textarea form-control m-b" rows="3" name="comment[content]"></textarea>
  <input type="submit" value="Submit" class="btn btn-secondary">
</form>
</div>
 -->


<%= form_with model: @comment, url:product_comments_path(product) do |f| %>

  <%= f.text_field :content,  class: "form-control"%>
  <%= f.submit "Comment", class: "btn btn-primary"%>
<% end %>

app/views/comments/create.js.erb
$('#comment').html("<%= escape_javascript(render('comments/comment'))%>")
$('#comment').html("<%= escape_javascript(render('comments/form'))%>")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user %></td>
        <td><%= comment.product %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @comment.product %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>