config/routes.rb
Rails.application.routes.draw do
  get 'search' , to: 'search#index'
  get 'shops/index'
  get 'shops/show'
  # resources :carts
  get 'carts', to: 'carts#index'
  resources :comments
  resources :products
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :line_items
  # resource :carts, only:[:show]
  resources :orders, only: [:index, :create, :show]
  resources :shops, only:[:index]
  root 'products#index'
  resources :orders, only: [:index, :show, :create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all

    @cart_item = current_cart.line_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', shop_path(product) %></td>

        <td>

          <%= form_for @cart_item, remote: true  do |f|%>
          <%= f.hidden_field :product_id, :value => product.id %>
          <%= f.number_field :quantity, :value => 1, :min =>  1%>
          <%= f.submit "Add to Cart "%>

        <form action="/line_items" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="line_item[product_id]" value="<%= product.id %>">
        <input type="hidden" name="line_item[quantity]" value="1">
        <input type="submit" value="Add to Cart" class="btn btn-primary">
        </form>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="card">
  <%= render 'carts/carts'%>
</div>

app/views/shops/show.html.erb
<h1>Shops#show</h1>
<p>Find me in app/views/shops/show.html.erb</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<% @product.line_items.each do |item| %>
  <%= item.quantity %>
<% end %>

<%= link_to 'Back', root_path %>