config/routes.rb
Rails.application.routes.draw do
  get 'search' , to: 'search#index'
  get 'shops/index'
  get 'shops/show'
  # resources :carts
  get 'carts', to: 'carts#index'
  resources :comments
  resources :products
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :line_items
  # resource :carts, only:[:show]
  resources :orders, only: [:index, :create, :show]
  resources :shops, only:[:index]
  root 'products#index'
  resources :orders, only: [:index, :show, :create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user ,  optional: true  # optional: true  =>  user can be nil
  has_many :line_items , as: :line_itemable, dependent: :destroy
  has_many :products, through: :line_items
  before_save :set_subtotal

  def sub_total
    line_items.collect{|line_item| line_item.valid? ? line_item.unit_price*line_item.quantity : 0}.sum
  end

  private

  def set_subtotal
    self[:sub_total] = sub_total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @line_items = current_cart.line_items
  end

  # def show
  #   @cart_items = current_cart.line_items
  #   # if Cart.exists?(session[:cart_id])
  #   #   @cart_items = current_cart.line_items
  #   # else
  #   #   @cart_items = session[:cart]
  #   #   # @cart_items = current_cart.line_items
  #   # end
  # end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_carts.html.erb
<%= link_to "#{current_cart.line_items.size} items with a value of #{current_cart.sub_total }$", carts_path%>

app/views/carts/_carts_item.html.erb
<h1>Cards#show</h1>
<p>Find me in app/views/cards/show.html.erb</p>

<%if @cart_items.count > 0 %>

  <% @cart_items.each do |item| %>

    <h3><%= item.product.name %></h3>
    <h5><%= item.product.price %></h5>



    <%= form_for item, remote: true do |f| %>

        <%= f.hidden_field :product_id, :value => item.product.id %>
        <%= f.number_field :quantity, :value => item.quantity.to_i %>
        <%= f.submit "Update Card " %>

        <%= link_to "Remove Items", line_item_path(item), method: :delete, remote: true%>

    <% end %>
    <h2>Subtotal: <%= item.total %></h2>

  <% end %>
<%else%>
  <h2>No Items in Cart</h2>
<%end%>


<h3>Your current card value has a subtotal of: <%= current_cart.sub_total %></h3>

app/views/carts/_total.html.erb
<div class="card">
  <div class="card-header text-center">
    Cart
  </div>
  <div class="card-body">
    <h5 class="card-title">Line items</h5>
    <table class="table">
      <thead>
        <tr>
          <th>Produt</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Subtotal</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.line_items.each do |line_item| %>
          <tr>
            <td><%= line_item.product.name %></td>
            <td><%= form_for line_item, remote: true do |f| %>

        <%= f.hidden_field :product_id, :value => line_item.product.id %>
        <%= f.number_field :quantity, :value => line_item.quantity.to_i, min:1 %>
        <%= f.submit "Update Card",class: 'btn btn-primary' %>
        <%end%>
        </td>
            <td><%= number_to_currency(line_item.unit_price) %></td>
            <td><%= number_to_currency(line_item.total) %></td>
            <td>
              <%= link_to "Remove", line_item_path(line_item), method: :delete, id: 'delete' , class: 'btn btn-danger del', data: { confirm: 'Are you sure?' , remote: true } %>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <h5 class="card-title">Total: <%= number_to_currency(current_cart.sub_total) %></h5>
    <%= link_to "Continue shopping", products_path, class: 'btn btn-primary' %>
    <% unless current_cart.line_items.empty? %>
      <%= link_to "Checkout", root_path, class: 'btn btn-success', method: :post  %>
    <% end  %>
  </div>
</div>

app/views/carts/index.html.erb
<div id="card-item">
  <%= render 'total'%>
</div>

app/views/carts/show.html.erb
<div id="card-item">
  <%= render 'carts_item'%>
</div>