config/routes.rb
Rails.application.routes.draw do
  get 'search' , to: 'search#index'
  get 'shops/index'
  get 'shops/show'
  # resources :carts
  get 'carts', to: 'carts#index'
  resources :comments
  resources :products
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :line_items
  # resource :carts, only:[:show]
  resources :orders, only: [:index, :create, :show]
  resources :shops, only:[:index]
  root 'products#index'
  resources :orders, only: [:index, :show, :create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :orders
  has_many :carts
  has_many :carts, through: :line_items
  has_many :line_items , as: :line_itemable
  has_many :orders, through: :line_items
  has_one_attached :main_image
  has_many_attached :other_images
  validates :name, presence: true
  validates :description, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
  validates :main_image, presence: true

  def self.search(search)
    if search
      # Product.find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

  def image_resize
    return self.main_image.variant(resize: '300x300!').processed
  end

  def image_resize_other
    return self.other_images.variant(resize: '300x300!').processed
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy,:my_products]
  skip_before_action :verify_authenticity_token
  # before_action :filter_products, only: [:my_products]

  # GET /products or /products.json
  def index
    @products = Product.search(params[:search])

  end

  # GET /products/1 or /products/1.json
  def show
    @comments = Comment.where(product_id: @product.id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @products = Product.where("name LIKE ?", "%#{params[:q]}%")
    render :index
  end

  def search_by_category
    @products = Product.where("category LIKE ?", "%#{params[:q]}%")
    render :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def authenticate_user!
      if !user_signed_in?
        redirect_to new_user_session_path
      end
    end


    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :picture, :quantity, :price, :user_id,
         :main_image, other_images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name,  class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description ,  class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :picture %>
    <%= form.text_field :picture,  class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity,  class:"form-control", min:0 %>
  </div>

  <div class="field form-group">
    <%= form.label :price %>
    <%= form.number_field :price , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id,  class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  <div class="field form-group">
  <%= form.label :main_image %>
  <%= form.file_field :main_image,  class:"form-control" %>
</div>

<div class="field form-group">
  <%= form.label :other_images %>
  <%= form.file_field :other_images, multiple: true,  class:"form-control" %>
</div>

  <div class="actions btn">
    <%= form.submit "Submit", class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%if @product.user_id==current_user.id %>
<h1>Editing Product</h1>
  <%= render 'form', product: @product %>

    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', products_path %>
<% else %>
<h1>Page Not Found</h1>
  <%= link_to 'Back', products_path %>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>
<div class="product-container ">
  <% @products.each do |product| %>
       <div class="product-card card primary">

          <% if product.main_image.attached? %>
            <%= image_tag product.image_resize,class:'card-img' %>
          <%else%>
            <img src="img/service3.png" alt="<%=product.name%>">
          <% end %>
            <h2><%= product.name %> <span><span><%=product.price%>$</span></span></h2>
            <h4><%= product.description %></h4>
          <%if user_signed_in? && product.user_id==current_user.id %>
              you cannot add your own product to cart
          <%else%>
            <% if product.quantity > 0 %>
              <form action="/line_items" method="post">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" name="line_item[product_id]" value="<%= product.id %>">
              <input type="hidden" name="line_item[quantity]" value="1">
              <input type="submit" value="Add to Cart" class="btn btn-primary">
              </form>


            <% else %>
              Out of stock
            <% end %>

            <%end%>
            <%= link_to 'Show', product, class:'btn' %>
          <br>
       </div>
  <% end %>
</div>
<br>

app/views/products/my_products.html.erb
<h1>Products</h1>
<div class="product-container ">
    <% @products.each do |product| %>
    <%if product.user_id == current_user.id%>
       <div class="product-card card primary">
          <img src="img/service3.png">
          <h2><%= product.name %> <span><%= product.price %></span></h2>
          <h4><%= product.description %></h4>
          <%= link_to 'Show', product %>
          <% if product.quantity > 0 %>
            <%# <%= link_to 'Add to cart', cart_path(product_id: product.id) %> %>
          <% else %>
              Out of stock
          <% end %>
       </div>
       <%end%>
    <% end %>
</div>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<main class="product-container">
  <div class="left-column">

  <% if @product.main_image.attached? %>
    <%= image_tag @product.image_resize ,class:'active card-img-show' %>
  <% end %>

  </div>
  <!-- Right Column -->
  <div class="right-column">

    <!-- Product Description -->
    <div class="product-description">
      <span>Categories Will be Display Here</span>
      <h1><%= @product.name %></h1>
      <p>  <%= @product.description %></p>
    </div>

    <!-- Product Configuration -->
    <div class="product-configuration">

    <!-- Product Pricing -->
    <div class="product-price">
      <span><%=@product.price%>$</span>
      <% if @product.quantity > 0%>
              <form action="/line_items" method="post">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" name="line_item[product_id]" value="<%= @product.id %>">
              <input type="hidden" name="line_item[quantity]" value="1">
              <input type="submit" value="Add to Cart" class="btn card-btn btn-primary ">
              </form>

          <% else %>
              Out of stock
          <% end %>
    </div>
  </div>
</main>


<%if current_user %>
  <%if @product.user_id != current_user.id %>

  <div class="card mb-3">
    <div class="card-header">
        <h4>Comments:</h4>
    </div>

    <div id="comments" class="card-body">
        <%= render @product.comments %>
        <%= render "comments/form", product: @product %>
    </div>
  </div>
  <%else%>

  <h1>You cannot Add Comment</h1>
  <br>
  <div class="card mb-3">
    <div class="card-header">
        <h4>Comments:</h4>
    </div>

    <div id="comments" class="card-body">
        <%= render @product.comments %>
    </div>
  </div>
  <%end%>

<%end%>

<%if !current_user %>
  <h1>You must be logged in to add comment</h1>
  <br>
  <div class="card mb-3">
    <div class="card-header">
        <h4>Comments:</h4>
    </div>

    <div id="comments" class="card-body">
        <%= render @product.comments %>
    </div>
  </div>
<%end%>


<br>
<%if current_user%>
  <%if @product.user_id==current_user.id %>
    <%= link_to 'Edit', edit_product_path(@product) %>   |
  <%end%>
<%end%>

<%= link_to 'Back', products_path %>